# Configuration file for stylua

# Indentation settings
indent_type = "Spaces"  # or "Tabs"
indent_width = 2        # number of spaces to use for indentation

# Line settings
column_width = 100       # maximum line width
line_endings = "Unix"   # or "Windows"
